### ISSUE TITLE
Missing APIs

### ISSUE THREAD

**Issue by davidt99** [mixpanel/mixpanel-python#107]
I'm missing insight and engagement specifically. Is it planned?

**Comment by jaredmixpanel** [comment]
@davidt99 `/insights`  and `/engage` are query API's for retrieving information _out of_ Mixpanel, this SDK is a tracking SDK for sending data _to_ Mixpanel. We do have a tracking API named `/engage` as well, and the various `people_*` methods in this SDK will send data to that API.

You may want to take a look at our `mixpanel-utils` library: https://github.com/mixpanel/mixpanel-utils

It doesn't have support for `/insights` or other formatted reports, but it is focused on importing/exporting your raw data.
