### ISSUE TITLE
how to do mixpanelGetEventsForProfiles

### ISSUE THREAD

**Issue by naarkhoo** [mixpanel/mixpanel-python#108]
seems `mixpanelGetEventsForProfiles` is available in R but not in python.

basically
Is there any way to export Mixpanel's Activity Feed data into CSV form?
I need one sheet for each user, displaying all the activity that user has performed on my site.

I've seen many ways to export general user data and funnel reports but not much on user activity feeds.

**Comment by jaredmixpanel** [comment]
@naarkhoo This is a tracking library for sending data to Mixpanel. For exporting data, see the mixpanel-utils library: https://github.com/mixpanel/mixpanel-utils

And more specifically, see the `export_events` method: https://github.com/mixpanel/mixpanel-utils#export-events
