### ISSUE TITLE
mixpanel.MixpanelException: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by rahultoora** [mixpanel/mixpanel-python#127]
Using python 3.10.10 and mixpanel 4.10.0

Have been seeing this Error pop up in our production application over last few months using the .track method.

More error details:

six.raise_from(MixpanelException(e), e)
mixpanel.MixpanelException: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
mixpanel.MixpanelException: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /track (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')))

The error does not always occur so am struggling to pinpoint the reason for sporadic failures

think this might resolve: 
https://github.com/mixpanel/mixpanel-python/issues/104#issuecomment-1262808130
https://github.com/mixpanel/mixpanel-python/pull/116/files

**Comment by aelamran** [comment]
happening to me too

**Comment by rahultoora** [comment]
> aelamran

Doesnt look like they maintain the python library anymore

**Comment by jaredmixpanel** [comment]
Just released v4.10.1 which includes https://github.com/mixpanel/mixpanel-python/pull/123 that hopefully fixes the issue. Feel free to reopen if not.

**Comment by aelamran** [comment]
@jaredmixpanel 
Thank you for the release, I'll be testing this out.
FYI; the latest release was not updated on the repository.
