### ISSUE TITLE
443 max retries exceeded error ['[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol]

### ISSUE THREAD

**Issue by aelamran** [mixpanel/mixpanel-python#128]
`mixpanel.MixpanelException: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /track (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))`

I have this intermittent error in production when using `mp.track`

Any ideas why is this happening?

**Comment by Erybor** [comment]
I have the exact same issue, is this library still supported or should I look into a different analytics tool?

**Comment by jaredmixpanel** [comment]
Make sure you are using the latest version `v4.10.1` which includes a fix that should address this issue: https://github.com/mixpanel/mixpanel-python/issues/127#issuecomment-1986537906
