### ISSUE TITLE
Import Legacy Data

### ISSUE THREAD

**Issue by cooncesean** [mixpanel/mixpanel-python#21]
Provide functionality to import data into Mixpanel older than 5 days.

**Comment by zakj** [comment]
@cooncesean Take a look at `Mixpanel.import_data`; it's got a slightly different API from `.track`, but it does allow importing older data. There's a bit more info available in [our import documentation][docs]. Please let me know if that's not working for you!

[docs]: https://mixpanel.com/docs/api-documentation/importing-events-older-than-31-days

**Comment by zakj** [comment]
@cooncesean Ha, I see now that `import_data` actually came from your PR... so, thanks again for that, and sorry for missing it the first time around. ;)

**Comment by cooncesean** [comment]
No worries and thanks for following up!

Glad it was merged and hopefully it makes the library a bit more robust :)
