### ISSUE TITLE
Can't use mutable data types for function defaults

### ISSUE THREAD

**Issue by eriktaubeneck** [mixpanel/mixpanel-python#29]
Many of the methods in the API use `{}` as a function default, however this can lead to serious issues. See [this blog post](http://pythonconquerstheuniverse.wordpress.com/category/python-gotchas/) on this python gotcha.  You should use `None` and then, for example in `track` call `all_properties.update(properties or {})`.

Without this, subsequent calls that don't provide properties, after one that does, will send the old properties along, which will lead to all sorts of confusion. :confounded:

**Comment by zakj** [comment]
Fixed in 6d14baf.
