### ISSUE TITLE
Fail to install 4.0.1 due to missing README.md

### ISSUE THREAD

**Issue by phaseburn** [mixpanel/mixpanel-python#45]
$ sudo easy_install mixpanel-py
Searching for mixpanel-py
Reading https://pypi.python.org/simple/mixpanel-py/
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-2.0.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-2.0.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-3.0.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-3.1.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-3.1.2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-3.1.3)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-3.2.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-3.2.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-4.0.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Library/Python/2.7/site-packages/setuptools-12.4-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'mixpanel (py-4.0.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Best match: mixpanel-py 4.0.1
Downloading https://pypi.python.org/packages/source/m/mixpanel-py/mixpanel-py-4.0.1.tar.gz#md5=e9d45a9aa82f95e84c960259a9c4d520
Processing mixpanel-py-4.0.1.tar.gz
Writing /tmp/easy_install-UsdqLT/mixpanel-py-4.0.1/setup.cfg
Running mixpanel-py-4.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UsdqLT/mixpanel-py-4.0.1/egg-dist-tmp-zhhP_i
error: README.md: No such file or directory
$

I would normally in such circumstances attempt to read the README file to see if I did something wrong, but, alas, I can't even do that.

**Comment by zakj** [comment]
Yeesh! Thanks so much for reporting this; 4.0.2 corrects the problem and is available now.
