### ISSUE TITLE
Add documentation for people_set's meta argument

### ISSUE THREAD

**Issue by gracaninja** [mixpanel/mixpanel-python#47]
Hello,

I am trying to do a server side update and I don't want the last seen time to be changed.

I am calling my update with the flag $ignore_time to True but it is still updating the last seen. Am I doing something wrong?

Here is some code:

def get_people_dict(user):
    try:
        birth_date_string = convert_datetime_to_string(user.date_of_birth)
    except:
        birth_date_string = convert_datetime_to_string(datetime.date.today())

    topics = [t.title for t in user.topics]
    people_dict = {}
    people_dict["$username"] = user.username
    people_dict["$first_name"] = user.first_name
    people_dict["$last_name"] = user.last_name
    people_dict["$email"] = user.email
    people_dict["$created"] = convert_datetime_to_string(user.date_joined)
    people_dict["$ip"] = convert_datetime_to_string(user.current_ip)
    people_dict["country"] = user.country
    people_dict["date_of_birth"] = birth_date_string
    people_dict["rating"] = user.rating
    people_dict["topics"] = topics
    people_dict["is_client"] = user.is_client
    people_dict["is_editor"] = user.is_editor
    people_dict["total_jobs"] = user.total_jobs
    people_dict["total_spent_money"] = round(user.total_spent_money, 1)
    people_dict["level"] = user.user_level.level_id
    people_dict["activated"] = user.active
    if user.native_language:
        people_dict["native_language"] = user.native_language.shortname
    people_dict["is_senior_editor"] = user.is_senior_editor
    people_dict["can_give_feedback"] = user.can_give_feedback
    people_dict["is_copy_editor"] = user.is_copy_editor
    people_dict = get_people_lang_pair_dict(user, people_dict)
    people_dict["balance"] = round(user.get_balance(), 1)
    # Do not update last seen
    people_dict["$ignore_time"] = True
    return people_dict

connection.people_set(user.username, people_dict)

**Comment by zakj** [comment]
Hi @gracaninja, thanks so much for this report! It's actually a bit confusing, but `Mixpanel.people_set`—in fact, all of the `people_*` methods—accepts two arguments. The first contains the data to set on the people profile, and the second one (`meta`) manages metadata about the operation itself. Our [HTTP API Reference](https://mixpanel.com/help/reference/http#people-analytics-updates) lists properties that need to be set in the `meta` dict. It looks like the relevant ones in your case are `$ip` and `$ignore_time`, so you'll want to make a call like:

```python
connection.people_set(user.username, people_dict, meta={
    '$ip': convert_datetime_to_string(user.current_ip),
    '$ignore_time': True,
})
```

This definitely ought to be in the `mixpanel-python` docs! I'll update the title of this issue to reflect that.

**Comment by gracaninja** [comment]
Thanks it worked.
