### ISSUE TITLE
Incorrect documentation for people_track_charge(...)

### ISSUE THREAD

**Issue by eKIK** [mixpanel/mixpanel-python#53]
The current version of mixpanel on pypi is 4.0.2. at the time of writing.

The documentation (http://mixpanel.github.io/mixpanel-python/#mixpanel.Mixpanel.people_track_charge) depicts the behavior for 4.0.2+ though since the handling of the properties=None changed there (https://github.com/mixpanel/mixpanel-python/commit/d92dd5faf69f3a743c093396e8699f6747efbadf).

Possible solutions:
1. Update the documentation and change the function signature to: people_track_charge(distinct_id, amount, properties, meta=None)
OR
2. Release version 4.0.3.

**Comment by avoid3d** [comment]
I'm not exactly sure as to the history/context of this is but the current version of the library with properties=None in the function signature, then tries to do properties.update(...) in the code, which of course will error out if properties hasn't been passed in.

**Comment by zakj** [comment]
Thanks for the report, @eKIK, and apologies for the confusion. I've published 4.1.0 to PyPI: (https://pypi.python.org/pypi/mixpanel). Note that the library has moved from `mixpanel-py` to `mixpanel` on PyPI.

**Comment by eKIK** [comment]
That's great, thanks @zakj
