### ISSUE TITLE
Unspecified requirement

### ISSUE THREAD

**Issue by leonsas** [mixpanel/mixpanel-python#57]
I was getting the following error:

```
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mixpanel/__init__.py", line 24, in <module>
    from six.moves import urllib
ImportError: cannot import name urllib
```

Easily fixed with `pip install six --upgrade`, so you guys might want to add a `requirements.txt` file. I'm on Python 2.7.9.

**Comment by zakj** [comment]
Great catch, thanks! We've got the dependency specified in `setup.py`, but it looks like you had a pre-1.4.0 version of `six` installed and we're not specifying a minimum version. I'll track down what we actually require and get it updated.

**Comment by zakj** [comment]
Thanks again for this report; finally updated `setup.py` in cc8e884.
