### ISSUE TITLE
__init__() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by powerfool** [mixpanel/mixpanel-python#61]
I'm getting this error trying to initialize Mixpanel.
Any idea what might be wrong?

![screenshot 2016-02-22 18 19 25](https://cloud.githubusercontent.com/assets/1142077/13224381/f55d3c92-d990-11e5-8afd-734f369eb3d1.png)

I installed using pip and then did:
```
from mixpanel import Mixpanel
mp = Mixpanel('1234567890')
```

Thanks for any tips!

**Comment by zakj** [comment]
Hey @powerfool, it sounds like you may have inadvertently installed the [mixpanel-python](https://pypi.python.org/pypi/mixpanel-python) package via pip, rather than this package which is just called [mixpanel](https://pypi.python.org/pypi/mixpanel). Unfortunately we don't control the former.

**Comment by powerfool** [comment]
Hi @zakj, I should have been more clear. I had done `pip install mixpanel` prior to importing it and trying to use it as above.
Thanks!

**Comment by zakj** [comment]
Sorry to have closed so quickly! I don't believe our `Mixpanel` class has ever required more than the `token` argument, but let's verify what version you have installed. Can you show me the output of this command?

```
python -c 'import mixpanel; print(mixpanel.VERSION, mixpanel.__file__)'
```

**Comment by powerfool** [comment]
It is resolved for me and it's quite ridiculous what was wrong, really. For some reason that I don't remember I had some leftover version of a mixpanel library in my working directory, conveniently named _mixpanel.py_. So even though I had the latest version in my virtualenv, during import that old one was being used. 
So, yeah, quite silly, let's keep this between us and the rest of the web.
Thank you for getting back to me anyway, I appreciate :)

**Comment by zakj** [comment]
No worries, we'll just pretend this never happened. ;)
