### ISSUE TITLE
using import_data with Buffered consumer is not working

### ISSUE THREAD

**Issue by eilonle** [mixpanel/mixpanel-python#62]
the send function used by the default consumer got the api_key as a parameter , the send function used by the Buffered consumer does not . So if you will try to run the import data with the Buffered Consumer it will result in an error.

**Comment by zakj** [comment]
Good catch, thanks! I'll get a new release out this week to fix the problem.

**Comment by zakj** [comment]
Fixed in 4.3.1.

**Comment by eilonle** [comment]
Great! thanks!
