### ISSUE TITLE
flush function for Buffered Consumer not working

### ISSUE THREAD

**Issue by eilonle** [mixpanel/mixpanel-python#63]
Hi,
in class BufferedConsumer the flush function in line 338 should change to 
def flush (self,api_key=None) 

and then in line 444-445 should change to:
        for endpoint in self._buffers.keys():
            self._flush_endpoint(endpoint,api_key=api_key)

**Comment by kidphys** [comment]
+1

I have the same issue. The exception is: "Mixpanel error: token, missing or empty" because of this bug.

**Comment by jkochaniak** [comment]
+1 I also just ran into this. Is it worth submitting a PR for this? I see 3 unmerged PRs that are a few years old.

**Comment by zakj** [comment]
Terribly sorry for the slow turnaround on this! Fixed in the just-released 4.3.2.
