### ISSUE TITLE
Support for querying

### ISSUE THREAD

**Issue by gregorypease280** [mixpanel/mixpanel-python#68]
It would be awesome if this library supported a way to grab some basic data from mixpanel (User profiles etc...), is this library still being developed?

**Comment by tdumitrescu** [comment]
You may like https://github.com/mixpanel/mixpanel_api. The tracking SDKs tend to stick to just sending data to Mixpanel i.e. the minimal code you want to add to your user-facing applications.

**Comment by gregorypease280** [comment]
@tdumitrescu lightning fast! thanks! I'll check it out
