### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by DataGreed** [mixpanel/mixpanel-python#79]
Since yesterday I've started receiving this error whenever I try to initialize mixpanel on my local machine.

This never happened the day before.

The full exception text:
```
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

File ".env/lib/python3.7/site-packages/mixpanel/__init__.py" in track
  95.         self._consumer.send('events', json_dumps(event, cls=self._serializer))

File ".env/lib/python3.7/site-packages/mixpanel/__init__.py" in send
  488.             self._write_request(self._endpoints[endpoint], json_message, api_key)

File ".env/lib/python3.7/site-packages/mixpanel/__init__.py" in _write_request
  511.             six.raise_from(MixpanelException(e), e)

File "<string>" in raise_from
  3. # Permission is hereby granted, free of charge, to any person obtaining a copy

```

**Comment by DataGreed** [comment]
The problem is that /usr/bin/python3 (from either Xcode or CLT) fails to correctly locate the trust store in /etc/ssl, as we can see using ssl.get_default_verify_paths() - this happens on macOS Catalina.

It's looking into /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/etc/ssl, which doesn't exist.

Quickfix:
```
/usr/bin/sudo /bin/mkdir /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/etc
/usr/bin/sudo /bin/ln -s /etc/ssl/ /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/etc/
```

Found at https://stackoverflow.com/questions/57630314/ssl-certificate-verify-failed-error-with-python3-on-macos-10-15

**Comment by seizethedave** [comment]
Yep that is a common snag with Python 3 on OS X. Thanks for the fix details.
