### ISSUE TITLE
deletion out of date

### ISSUE THREAD

**Issue by alekhrycaiko** [mixpanel/mixpanel-python#82]
Hi, we've had an occurrence on our system where we've found that $delete no longer takes an empty string like described in the line below. Instead, a boolean value is now needed. 

https://github.com/mixpanel/mixpanel-python/blob/e69ecf666af7f01b4e09c53bcd953e7c34382810/mixpanel/__init__.py#L302

If this is the case, this SDK should be updated.

**Comment by seizethedave** [comment]
Thanks @alekhrycaiko , but I'm not able to replicate this with the following script. Please let me know what I should do instead!

```
mp.people_set("user_c", {"$first_name": "Test"})
mp.track("user_c", "signup")
# then,
mp.people_delete("user_c")
```

David
