### ISSUE TITLE
question - do the SDKs only support creating events?

### ISSUE THREAD

**Issue by avnerbarr** [mixpanel/mixpanel-python#87]
I want to query cohorts and user data but it seems that the sdk only supports creating events.

Which SDKs  support the query side of the API?

**Comment by seizethedave** [comment]
That is right, this library is focused around writing to Mixpanel.
We don't really have an official Query API Python toolkit, but these libraries have some query ability:
- https://github.com/mixpanel/mixpanel_api
- https://github.com/cooncesean/mixpanel-query-py

Sorry for the late response!
