### ISSUE TITLE
import_data method not working

### ISSUE THREAD

**Issue by danhopwood** [mixpanel/mixpanel-python#88]
Hi there!

**Summary**: `track()` method works great, `import_data()` doesn't 😢 

The request appears to succeed – on inspecting the decoded response object it's `{'error': None, 'status': 1}` as expected

But in Mixpanel the data simply never shows up (I waited 24 hours in case it takes time to show)

I've only just noticed [the other repo](https://github.com/mixpanel/mixpanel_api) for importing/exporting but presumably `import_data` here should still work, right?

p.s. in case it helps, interestingly if I set my API secret to a random non-empty string, the request _still_ succeeds with no errors 🤔 

Any ideas? :)

**Comment by seizethedave** [comment]
Hi Dan, you're right. It's because we (not too long ago) started to guard the import endpoint with the Mixpanel project API secret sent via HTTP basic auth, rather than the old API key included in the JSON body. I'll prepare a fix. Thanks for the report.

**Comment by danhopwood** [comment]
That would be great, thanks!

I managed to work around it by calling the HTTP API directly but always nice to be able to just use the library :)

*Dan Hopwood*
Founder at Casey ( https://casey.app/ )

**Comment by silviogutierrez** [comment]
Also had this issue. So did this retroactively stop working? I would imagine a lot of projects now are not importing data.

As @danhopwood mentioned, it still responds with a successful response, no error. Just silently accepts it.

If that's the case, I think this is an urgent issue.

**Comment by seizethedave** [comment]
Thanks for the nudge, had a fix in the wings. I'll publish a new Python package after CI passes...
