### ISSUE TITLE
bufferedconsumer _api_secret problem

### ISSUE THREAD

**Issue by sanderland** [mixpanel/mixpanel-python#91]
BufferedConsumer has this code:

```python
        # Fixme: Don't stick these in the instance.
        self._api_key = api_key
        self._api_secret = api_secret
```
Classes that override send without setting these instance vars, such as your recommended AsyncBufferedConsumer, end up generating an error in `_flush_endpoint`

This could be considered an error in the async package as well (cf https://github.com/jessepollak/mixpanel-python-async/issues/18), but considering you have a FIXME here, I suppose a recent change broke the interaction.

**Comment by seizethedave** [comment]
Oh, that's a bummer. Thanks for looking into the cause.
I plan to overhaul this soon in a new major release. Until then, I will prepare a release to fix this snag.

**Comment by seizethedave** [comment]
4.8.1 is out, please let me know if it doesn't fix your problem @sanderland.
