### ISSUE TITLE
Dealing with new DeprecationWarning about using method_whitelist argument of Retry

### ISSUE THREAD

**Issue by lfrodrigues** [mixpanel/mixpanel-python#93]
You are using the method_whitelist init parameter of Retry. Version 1.26.0 of urllib3 introduced a replacement init parameter named allowed_methods and at the same time started issuing a DeprecationWarning for using method_whitelist.

The discussion and potentially fix in urllib3/urllib3#2057

**Comment by seizethedave** [comment]
Thanks! I will address this soon.

**Comment by seizethedave** [comment]
@lfrodrigues this should now be fixed in 4.8.2.
